title: "Azure Gold Studio"
description: "Diseño editorial, estrategia digital y arquitectura web para marcas de servicios."
baseurl: ""
url: "https://azurewebstudio.com"

markdown: kramdown
highlighter: rouge

# Permalinks limpios
permalink: /:categories/:title/

# Incluir carpetas necesarias
include:
  - _includes
  - _layouts
  - _posts

# Excluir archivos que no deben procesarse
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Activar colecciones si las necesitas
collections:
  casos:
    output: true
    permalink: /casos/:name/

# Configuración del blog
paginate: 10
paginate_path: "/blog/page:num/"

# Idioma
lang: es
